title: "halqery"
description: "Pokemon Legends: Arceus Speedrunner"

permalink: /:slug

twitter:
  username: halqery
  card: summary_large_image

theme_config:
  appearance: "dark"
  appearance_toggle: true
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_blog: true
  show_reading_time: true
  show_tags: true
  show_code_copy: true
  show_progress_bar: true
  show_back_to_top: true

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
